function DoctorsPage(){
    return <div>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
        <h1>Doctors</h1>
    </div>
}
export default DoctorsPage